default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Impress_development


test:
  <<: *default
  database: Impress_test
